name: build nginx for windows

# Officical Documentation:
# https://nginx.org/en/docs/howto_build_on_win32.html

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    
      - name: setup git
        uses: actions/checkout@v4.1.1
        
      - name: setup microsoft visual c
        uses: TheMrMilchmann/setup-msvc-dev@v3.0.0
        with:
          arch: x64
          
      - name: setup msys2
        uses: msys2/setup-msys2@v2
      
      - name: clone source code
        run: |
          c:
          git clone --branch=release-1.24.0 --depth=1 https://github.com/nginx/nginx
          cd nginx
          mkdir objs/lib
          cd objs/lib
          git clone --branch=pcre2-10.39 --depth=1 https://github.com/PCRE2Project/pcre2
          git clone --branch=v1.3 --depth=1 https://github.com/madler/zlib
          git clone --branch=openssl-3.0.10 --depth=1 https://github.com/openssl/openssl
          
      - name: configure
        shell: msys2 {0}
        run: |
          cd /c/nginx
          ./auto/configure \
          --with-cc=cl \
          --with-debug \
          --prefix= \
          --conf-path=conf/nginx.conf \
          --pid-path=logs/nginx.pid \
          --http-log-path=logs/access.log \
          --error-log-path=logs/error.log \
          --sbin-path=nginx.exe \
          --http-client-body-temp-path=temp/client_body_temp \
          --http-proxy-temp-path=temp/proxy_temp \
          --http-fastcgi-temp-path=temp/fastcgi_temp \
          --http-scgi-temp-path=temp/scgi_temp \
          --http-uwsgi-temp-path=temp/uwsgi_temp \
          --with-cc-opt=-DFD_SETSIZE=1024 \
          --with-pcre=objs/lib/pcre2 \
          --with-zlib=objs/lib/zlib \
          --with-openssl=objs/lib/openssl \
          --with-openssl-opt=no-asm \
          --with-http_ssl_module \
          --with-stream \
          --with-stream_ssl_module \
          --with-stream_ssl_preread_module \

      - name: make
        run: |
          c:
          cd nginx
          nmake
          
      - name: process output files
        run: |
          c:
          cd nginx
          xcopy objs\\nginx.exe to_pack\\
          xcopy /e docs\\text to_pack\\docs\\
          echo f | xcopy objs\\lib\\pcre2\\LICENCE to_pack\\docs\\PCRE.LICENCE
          echo f | xcopy objs\\lib\\zlib\\README to_pack\\docs\\zlib.LICENSE
          echo f | xcopy objs\\lib\\openssl\\LICENSE to_pack\\docs\\OpenSSL.LICENSE
          xcopy /e conf to_pack\\conf\\
          xcopy /e contrib to_pack\\contrib\\
          xcopy /e docs\\html to_pack\\html\\
          mkdir to_pack\\logs
          mkdir to_pack\\temp
          
      - name: package
        run: |
          c:
          cd nginx
          ren to_pack nginx_windows
          tar -c -f nginx_windows.tar nginx_windows
      
      - name: upload
        uses: actions/upload-artifact@v4.0.0
        with:
          name: nginx_windows.tar
          path: c:/nginx/nginx_windows.tar